language: node_js
node_js:
- '8.9.4'
sudo: required

env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - npm install -g typescript
  - npm install -g mocha 
  - $ORACLE_HOME/bin/sqlplus -S travis/travis <<SQL
script:
- npm test